version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pruebas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 586613
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:586613@db:5432/pruebas